// <auto-generated />
using CourierApplication.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourierApplication.Migrations
{
    [DbContext(typeof(CourierDbContext))]
    partial class CourierDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourierApplication.Model.Adress", b =>
                {
                    b.Property<int>("AdressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdressId");

                    b.ToTable("Adresses");

                    b.HasData(
                        new
                        {
                            AdressId = 1,
                            Latitude = 51.117193m,
                            Longitude = 17.044819m,
                            Name = "Sienkiewicza 13/4"
                        },
                        new
                        {
                            AdressId = 2,
                            Latitude = 51.114836m,
                            Longitude = 17.068532m,
                            Name = "Grunwaldzka 71/4"
                        },
                        new
                        {
                            AdressId = 3,
                            Latitude = 51.114899m,
                            Longitude = 17.001978m,
                            Name = "Legnicka 42/18"
                        },
                        new
                        {
                            AdressId = 4,
                            Latitude = 51.123066m,
                            Longitude = 17.049608m,
                            Name = "Nowowiejska 31/10"
                        },
                        new
                        {
                            AdressId = 5,
                            Latitude = 51.098380m,
                            Longitude = 16.936670m,
                            Name = "Rakietowa 20/9"
                        },
                        new
                        {
                            AdressId = 6,
                            Latitude = 51.065627m,
                            Longitude = 16.957833m,
                            Name = "Targowa 87/11"
                        },
                        new
                        {
                            AdressId = 7,
                            Latitude = 51.119083m,
                            Longitude = 16.978771m,
                            Name = "Bystrzycka 64/3"
                        },
                        new
                        {
                            AdressId = 8,
                            Latitude = 51.124014m,
                            Longitude = 16.960451m,
                            Name = "Bajana 82/16"
                        },
                        new
                        {
                            AdressId = 9,
                            Latitude = 51.069190m,
                            Longitude = 17.040798m,
                            Name = "Terenowa 8/2"
                        },
                        new
                        {
                            AdressId = 10,
                            Latitude = 51.135035m,
                            Longitude = 16.973569m,
                            Name = "Kolista 32/5"
                        },
                        new
                        {
                            AdressId = 11,
                            Latitude = 51.091435m,
                            Longitude = 17.008427m,
                            Name = "Pretficza 27/19"
                        },
                        new
                        {
                            AdressId = 12,
                            Latitude = 51.1259106m,
                            Longitude = 16.9693086m,
                            Name = "Drzewieckiego 24/29"
                        });
                });

            modelBuilder.Entity("CourierApplication.Model.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdressId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("AdressId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            AdressId = 1
                        },
                        new
                        {
                            ClientId = 2,
                            AdressId = 2
                        },
                        new
                        {
                            ClientId = 3,
                            AdressId = 3
                        },
                        new
                        {
                            ClientId = 4,
                            AdressId = 4
                        },
                        new
                        {
                            ClientId = 5,
                            AdressId = 5
                        },
                        new
                        {
                            ClientId = 6,
                            AdressId = 6
                        },
                        new
                        {
                            ClientId = 7,
                            AdressId = 7
                        },
                        new
                        {
                            ClientId = 8,
                            AdressId = 8
                        },
                        new
                        {
                            ClientId = 9,
                            AdressId = 9
                        },
                        new
                        {
                            ClientId = 10,
                            AdressId = 10
                        },
                        new
                        {
                            ClientId = 11,
                            AdressId = 11
                        },
                        new
                        {
                            ClientId = 12,
                            AdressId = 12
                        });
                });

            modelBuilder.Entity("CourierApplication.Model.Courier", b =>
                {
                    b.Property<int>("CourierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isFree")
                        .HasColumnType("bit");

                    b.HasKey("CourierId");

                    b.ToTable("Couriers");

                    b.HasData(
                        new
                        {
                            CourierId = 1,
                            FirstName = "Marcin",
                            LastName = "Kowalski",
                            isFree = true
                        },
                        new
                        {
                            CourierId = 2,
                            FirstName = "Tomasz",
                            LastName = "Nowak",
                            isFree = true
                        },
                        new
                        {
                            CourierId = 3,
                            FirstName = "Tomasz",
                            LastName = "Gajda",
                            isFree = false
                        });
                });

            modelBuilder.Entity("CourierApplication.Model.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdressId")
                        .HasColumnType("int");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("bit");

                    b.HasKey("OrderId");

                    b.HasIndex("AdressId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            AdressId = 2,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 2,
                            AdressId = 10,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 3,
                            AdressId = 5,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 4,
                            AdressId = 8,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 5,
                            AdressId = 9,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 6,
                            AdressId = 10,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 7,
                            AdressId = 10,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 8,
                            AdressId = 3,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 9,
                            AdressId = 11,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 10,
                            AdressId = 4,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 11,
                            AdressId = 12,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 12,
                            AdressId = 6,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 13,
                            AdressId = 7,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 14,
                            AdressId = 3,
                            isCompleted = false
                        },
                        new
                        {
                            OrderId = 15,
                            AdressId = 5,
                            isCompleted = false
                        });
                });

            modelBuilder.Entity("CourierApplication.Model.Client", b =>
                {
                    b.HasOne("CourierApplication.Model.Adress", "Adress")
                        .WithMany("Client")
                        .HasForeignKey("AdressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourierApplication.Model.Order", b =>
                {
                    b.HasOne("CourierApplication.Model.Adress", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
